name: 'Run Python Script'
description: 'Run the specified python script'

inputs:
  script-path:
    description: 'Python script path'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run python file
      shell: bash
      run: python ${{ inputs.script-path }}
